enabled: true
copyright: 'Copyright &copy; Your Website 2016'
favicon: favicon.png
error_header_image: home-bg.jpg
social_icons:
  -
    icon: fa-twitter
    url: 'https://www.twitter.com/'
  -
    icon: fa-facebook
    url: 'https://www.facebook.com/'
  -
    icon: fa-github
    url: 'https://www.github.com/'
